Feature : 5. Working with data 번역 documentation
SoogoonSoogoonPythonists/sqlalchemy-for-pythonist pull request #18
Opened 2021-07-22 14:26 UTC by icehongssii

2021-07-23 11:18 UTC, Hyeonproject commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +Core와 ORM을 이용해 데이터 Select하기 - 이번 섹션은 SQLAlchemy에서 가장 자주 쓰이느 Select 생성자에 대해서 다룹니다. Select 생성자는 Core 및 ORM을 이용한 어플리케이션 구문을 반환합니다.
```suggestion
Core와 ORM을 이용해 데이터 Select하기 - 이번 섹션은 SQLAlchemy에서 가장 자주 쓰이는 Select 생성자에 대해서 다룹니다. Select 생성자는 Core 및 ORM을 이용한 어플리케이션 구문을 반환합니다.
```
쓰이는이 맞는 맞춤법이라고 생각해서 리뷰했습니다. ^^

2021-07-23 11:59 UTC, heumsi requested changes
저는 일단 오늘 `FROM절과 JOIN 명시하기` 전까지만 리뷰하겠습니다.

- 전반적으로 마크다운 인라인 코드블락(`) 안 사용한 부분은 고쳐주시면 좋겠습니다.
- 인라인 코드블락 빠진 부분이 자주보이는데, 찾아서 넣어주시면 좋을거 같아요.
- 렌더링된 문서 한번 쫙 보시면서 이상한 부분 잡아주시면 좋을거 같슴다.

내일 마저 리뷰할게요.

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +# 5. 데이터 select하기
```suggestion
# 5. 데이터 핸들링 - Core, ORM으로 행 조회하기
```

좀 더 목적지향적, 직관적인 문체로 바꿔 보았습니다.
파일 이름도 이걸로 바꿔주시면 좋을거 같아요.

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +Core와 ORM을 이용해 데이터 Select하기 - 이번 섹션은 SQLAlchemy에서 가장 자주 쓰이는 Select 생성자에 대해서 다룹니다. Select 생성자는 Core 및� ORM을 이용한 어플리케이션 구문을 반환합니다.
```suggestion
이번 섹션에서는 SQLAlchemy에서 가장 자주 쓰이는 Select에 대해서 다룹니다.
```

간결 + 특수 문자 제거했습니다.

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +(user_table.c.name == 'spongebob')
```suggestion
(user_table.c.name == 'spongebob')  # name 컬럼에 접근하고 싶다면 테이블명.c.name
```

주석이 코드 옆으로 가는게 가독성이 좋아보여용

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +>>> print(stmt)
```suggestion
>>> print(stmt)
"""
SELECT user_account.id, user_account.name, user_account.fullname
FROM user_account
WHERE user_account.name = :name_1
"""
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +완전한 엔티티를 포함하는 결과를 반환합니다.
> 완전한 엔티티를 포함하는 결과를 반환합니다.

완전한 엔티티가 뭔가요?? 위에랑 구체적으로 어떤 차이가 있는거에요? 이를 좀 더 적어주시면 좋을거 같아요!

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +<code>Table.c</code> 접근자(accessor)에서 <code>column</code>객체에 접근합니다.
이게 무슨 말인지 잘 모르겠어요 ㅜ
말로 하는거 보다 그냥 코드 예시로 한방에 보여주면 좋을거 같은데...

여기서 한번에 설명할 수 없다면 이 구문은 차라리 생략해버리는 것도 좋을거 같습니다.

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +### ORM 엔티티와 and 컬럼 조회하기
```suggestion
### ORM 엔터티 및 열 조회
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> + ORM <code>Session.execute()</code>메서드를 이용해 쿼리문을 실행 시킬 때 <code>User</code> 클래스와 같은 전체 엔티티를 사용하면 결과 세트에서
```suggestion
 ORM `Session.execute()` 메서드를 이용해 쿼리문을 실행 시킬 때 `User` 클래스와 같은 전체 엔티티를 사용하면 결과 세트에서 
```

마크다운으로 수정했습니다.

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +>>> row = session.execute(select(User)).first
```suggestion
>>> row = session.execute(select(User)).first()
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +또는 클래스 바인딩 어트리뷰트를 사용하여 결과물 <code>row</code>내의 ORM 엔티티 컬럼을 select 할 수 있습니다.
```suggestion
또는 엔티티 속성을 이용하여 `row` 내의 ORM 엔티티 컬럼을 가져올 수 있습니다.
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +...         ("Username: " + user_table.c.name).label("username"),
`("Username: " + user_table.c.name)` 

이렇게 문자열과 `ColumnElement` 를 `+` 연산하면 `ColumnElement` 가 나오나요??

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +아래는 text() 생성자를 이용해 `some label`과 함께 특정 컬럼을 같이 출력하는 예제입니다.
```suggestion
아래는 `text()` 생성자를 이용해 `some label`과 함께 특정 컬럼을 같이 출력하는 예제입니다.
```

코드 구문은 인라인  코드블락으로 만들어주시면 가독성 좋습니다.  
다른 부분들도 마찬가지입니당 ㅎㅎ

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +('some phrase', 'patrick'), ('some phrase', 'sandy'), ('some phrase', 'spongebob')]
```suggestion
[('some phrase', 'patrick'), ('some phrase', 'sandy'), ('some phrase', 'spongebob')]
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +하지만 일반적으로 literal_column() 생성자를 이용하면 스트링 문자열을 출력하는데 더 편리한 기능을 제공해줍니다.
```suggestion
하지만 일반적으로 `literal_column()` 생성자를 이용하면 스트링 문자열을 출력하는데 더 편리한 기능을 제공해줍니다.
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +이 생성자는 text() 와 매우 비슷하지만,
```suggestion
이 생성자는 `text()` 와 매우 비슷하지만, 
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +<code>column</code>을 표시하고 서브쿼리를 이용 할 수 있게 라벨 기능을을 제공합니다.
```suggestion
`column`을 표시하고 서브쿼리를 이용 할 수 있게 라벨 기능을 제공합니다.
```

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +user_account.name = :name_1
오.. `==` 연산자가 참/거짓을 판단하는 오퍼레이터로 안쓰이고 이렇게 표현되는게 신기하네요 ...

2021-07-23 11:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +
여기에 ``` 가 빠진듯해요

2021-07-24 06:59 UTC, heumsi requested changes
정리하시느라 정말 고생하셨습니다. 덕분에 잘 읽었어요.

리뷰할 점은...

1. 전반적으로 글을 다시 직접 읽어보시면서 비문, 번역되다 안된 곳, 오타, 마크다운 깨진곳 등을 보고 고쳐주시면 좋을거 같습니다.
2. 코드 블락에 쿼리 앞뒤로 `"""` 추가해주세용
3. 한글로 설명한 부분들이 잘 안읽힙니다. 본인도 다시 한번 읽어보시고, 무슨 말을 전달할지 간결하게 정리해주시면 좋을거 같습니다.

한글 설명을 한 부분들을 좀 더 풀어주시면 좋을거 같아요. 이 섹션을 읽는 분들은 아마도 조회 쿼리를 어떻게 SQLAlchemy로 사용할까? 어떻게 활용할 수 있을까? 어떤 사례들이 있지? 에 대해 관심이 많으실거에요. 물론 저같은 초보이실거구요! (당연히 SQL도 초보이실겁니다.) 이런 눈높이에 맞춰서 글을 좀 더 정리해주시면 좋을거 같아요. 본인이 이해는 했으나, 이 글에서 설명할 엄두가 안나면 다른 분들이 잘 정리해놓으신 글을 링크로 걸어주시면 좋습니다.

아마 하시면서 스스로 공부가 많이 되셨을텐데, 읽는 사람으로 하여금 그 지식들도 같이 공유받을 수 있도록 해주세요 ㅎㅎ

정리하시느라 고생하셨고, 피드백, 의견 등 주세요!

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +join을 이용해 두 개 이상의 테이블을 참조해 select 해야하는 경우가 있는데 이 상황에서 두 개의 메서드를 선택할 수 있다.
갑자기 존대 -> 반말로 변하는 문장들이 있는데, 이런 문체 모두 찾아서 바꿔주시면 좋을듯 해용

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +FROM 절은 보통 Select의 선택된 컬럼들에 있는 테이블을 렌더합니다.(table_name.column)
이 구문들이 무슨말인지 잘 모르겠어요.
우리가 무엇을 할 수 있는지만 말해주고, 코드만 보여주면 좋을거 같습니다.

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +FROM user_account JOIN address ON user_account.id = address.user_id
```suggestion
"""
SELECT address.email_address
FROM user_account JOIN address ON user_account.id = address.user_id
"""
```

파이썬 코드블락에 들어가는 문자열은 이렇게 `"""` 로 묶어주시면 좋을거 같아요.

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +한편 우리가 FROM절에 추가 옵션을 주고 싶을 때는 Select.select_frim()메서드를 사용합니다.
```suggestion
한편 우리가 FROM절에 추가 옵션을 주고 싶을 때는 `Select.select_from()` 메서드를 사용합니다.
```

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +FROM user_account JOIN address ON user_account.id = address.user_id
이렇게 적용안되어 있는 다른 부분들도 수정해주시면 좋을거 같아요. 따로 코멘트 달지 않을게요 ㅎㅎ

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +...         group_by("user_id").order_by("user_id", desc("num_addresses"))
```suggestion
...     Address.user_id,
...     func.count(Address.id).label('num_addresses')).\
...     group_by("user_id").order_by("user_id", desc("num_addresses"))
```

인덴트 맞춰주세용 ㅎㅎ

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +>>> user_alias_2 = user_table.alias()
`alias()` 의 결과물이 무엇인지 읽는 사람 입장에서는 모를거 같아요 ㅎㅎ
이건 언제 쓰이는거고, 용도가 정확히 뭘까요??

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +이 섹션에서는 일반적으로 SELECT의 FROM 절에 있는 서브 쿼리에 대해 설명합니다. 서브쿼리와 유사한 방식으로 사용되지만 추가 기능이 포함된 CTE도 다룹니다.
전 CTE에 대해서 처음 들어봤는데, 처음 알게된 사람을 위해서 참고 링크라도 남겨주시면 좋을거 같아요.

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +SQLAlchemy는 ScalarSelect 객체의 종류 중 하나로 Exists 객체를 갖고 있는데 이는 EXISTS 서브쿼리를 생성하고 SelectBase.exists()라는 메서드를 통해 Exists객첼르 생성할 수 있습니다.
```suggestion
`ScalarSelect` 객체의 종류 중 하나로 EXISTS 서브쿼리를 생성하는 `Exists` 객체가 있습니다. 이는 `SelectBase.exists()` 메서드를 통해 생성할 수 있습니다.
```

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +### 리턴 타입이 있는 함수Functions Have Return Types
이런거... 정리가 되다 안된 느낌인데, 전반적으로 이런 부분들 다시 한번 검토해주시면 좋을거 같아요.

2021-07-24 06:59 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +
```suggestion
<br>
```

2021-07-24 07:31 UTC, definity-smileY commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +완전한 엔티티를 포함하는 결과를 반환합니다.
```suggestion
한편 ORM을 이용해 select() 생성자를 사용할 때는 <code>Session.exeucte()</code>를 사용해야합니다.</br>
결과는 마찬가지로 <code>Row</code>객체를 반환하지만 완전한 엔티티를 포함하는 결과를 반환합니다.
```
가독성좋게 사용해보았습니다!

2021-07-24 07:31 UTC, definity-smileY commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +임의로 SQL 형식을 출력하기보다 보다 명시적으로 하나의
```suggestion
임의로 SQL 형식을 출력하기보단 보다 명시적으로 하나의
```

2021-07-24 07:31 UTC, definity-smileY commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +> 하지만 text() 또는 literal_column()을 사용한다는 것은  때는 리터럴 값이 아닌 SQL 구문을 사용한다는 뜻입니다. 따라서 우리는 렌더링하려는 SQL에 필요한 ""와 같은 쌍따옴표등을 추가해야합니다.
```suggestion
> 하지만 text() 또는 literal_column()을 사용한다는 것은 리터럴 값이 아닌 SQL 구문을 사용한다는 뜻입니다. 따라서 우리는 렌더링하려는 SQL에 필요한 ""와 같은 쌍따옴표등을 추가해야합니다.
```

2021-07-24 08:16 UTC, definity-smileY commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +SQL 함수 작업
```suggestion
### SQL 함수 작업
```

2021-07-24 08:16 UTC, definity-smileY commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +- <code>count()</code> : 집계 함수로 몇개의 행이 반환되었지 세서 그 수를 반환해줍니다.
```suggestion
- <code>count()</code> : 집계 함수로 반환된 행의 수를 반환해줍니다.
```

2021-07-24 08:16 UTC, definity-smileY commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +- <code>lower()</code> : 문자열 함수로 스트링 문자열을 소문자로 바꿔줍니다.
```suggestion
- <code>lower()</code> : 문자열 함수로 문자열을 소문자로 바꿔줍니다. 
또는 대문자 문자열을 소문자로 바꿔주기도 합니다.
```

2021-07-24 09:48 UTC, comnamu18 commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +임의로 SQL 형식을 출력하기보다 보다 명시적으로 하나의
```suggestion
임의로 SQL 형식을 출력하기보단 명시적으로 하나의
```

2021-07-24 09:48 UTC, comnamu18 commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +<code>ColumnElement.asc()</code><code>ColumnElement.desc()</code>를
```suggestion
<code>ColumnElement.asc()</code>, <code>ColumnElement.desc()</code>를
```
붙어있으니 조금 보기 불편하네요. 271번째 라인처럼 콤마를 통해서 구분지어주면 좋을 것 같습니다.

2021-07-24 09:48 UTC, comnamu18 commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +SQL에서 집계 함수를 사용하면 여러 행에 걸쳐 있는 합쳐 단일 결과를 생성할 수 있습니다. 예를 들어 카운팅, 평균 계산은 물론 값 집합에서 최대값 또는 최소값을 찾는 작업을 할 수 있다.
```suggestion
SQL에서 집계 함수를 사용하면 여러 행에 걸쳐 있는 데이터를 합쳐 단일 결과를 생성할 수 있습니다. 예를 들어 카운팅, 평균 계산은 물론 최대값 또는 최소값을 찾는 작업을 할 수 있습니다. 
```
데이터를 합치는 것 맞죠??
최대 최소의 경우 값 집합에서 찾는 것이 당연한 것 같아 빼봤습니다.

2021-07-24 09:48 UTC, comnamu18 commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +라벨을 통해 ordering, grouping하려면 스트링 텍스트의 이름을 <code>Select.order_by()</code> 또는 <code>Select.group_by()</code> 메서드에 전달하여 사용할 수 있습니다. 전달된 텍스트는 곧바로 렌더링되지 않습니다. 대신 컬럼절에 전잘 된 이름과 컨텍스트에 전달 된 이름이 일치하지 않으면 오류가
```suggestion
라벨을 통해 ordering, grouping하려면 스트링 텍스트의 이름을 <code>Select.order_by()</code> 또는 <code>Select.group_by()</code> 메서드에 전달하여 사용할 수 있습니다. 전달된 텍스트는 곧바로 렌더링되지 않습니다. 대신 컬럼절에 전달 된 이름과 컨텍스트에 전달 된 이름이 일치하지 않으면 오류가 발생합니다.
```

2021-07-24 09:48 UTC, comnamu18 commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +SQL EXISTS 키워드는  SELECT 문이 행을 반환하는지 여부에 따라 True 또는 false를 반환합니다.
```suggestion
SQL EXISTS 키워드는  SELECT 문이 행을 반환하는지 여부에 따라 True 또는 False를 반환합니다.
```

2021-07-24 09:48 UTC, comnamu18 commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +한편 특정 클래스의 함수는 특정 열을 참조해야 하는 경우 컬럼 값 대신 전체 행을 반환하는데 이러한 함수를
```suggestion
- 한편 특정 클래스의 함수는 특정 열을 참조해야 하는 경우, 컬럼 값 대신 전체 행을 반환하기도 합니다.  이러한 함수를 <Code>table valued functions. </code> 이라고 합니다.
```

2021-07-24 10:12 UTC, icehongssii commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +Core와 ORM을 이용해 데이터 Select하기 - 이번 섹션은 SQLAlchemy에서 가장 자주 쓰이는 Select 생성자에 대해서 다룹니다. Select 생성자는 Core 및� ORM을 이용한 어플리케이션 구문을 반환합니다.
아 ㅋㅋㅋㅋ 훨씬 간결하네요 감사합니다.

2021-07-24 10:27 UTC, icehongssii commented
#  TODO

##  예제에서 사용되고 있는 변수들 다시 정의 
```python
from sqlalchemy import MetaData
from sqlalchemy import Table, Column, Integer, String

metadata = MetaData()
user_table = Table(
    'user_account',
    metadata,
    Column('id', Integer, primary_key=True),
    Column('name', String(30)),
    Column('fullname', String),
)


```

2021-07-24 11:00 UTC, icehongssii commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +<code>Table.c</code> 접근자(accessor)에서 <code>column</code>객체에 접근합니다.
이 부분은 삭제하겠습니다

2021-07-24 15:24 UTC, icehongssii commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +...         ("Username: " + user_table.c.name).label("username"),
## 문자열 +  `Column` 하면 `BinaryExpression`객체가 나옵니다.
` user_table.c.name`은 `<class 'sqlalchemy.sql.schema.Column'>`인데
`"Username: " + user_table.c.name`하면 `<class 'sqlalchemy.sql.elements.BinaryExpression'>`되네요!!!
`+`하니까 타입이 `BinaryExpression`로 바껴요.


### `BinaryExpression`에 관한 공식 문서 
[BinaryExpression](https://docs.sqlalchemy.org/en/14/core/sqlelement.html?highlight=binaryexpression#sqlalchemy.sql.expression.BinaryExpression)
A `BinaryExpression` is generated automatically whenever two column expressions are used in a Python binary expression:

근데  string + column 해도 BinaryExpression 나옵니다 ㅎㅎ

```python 
>>> from sqlalchemy.sql import column
>>> column('a') + column('b')
<sqlalchemy.sql.expression.BinaryExpression object at 0x101029dd0>
>>> print(column('a') + column('b'))
a + b
```


### 튜토리얼에 나온 예제 
```python
from sqlalchemy import select, MetaData, Table, Column, Integer, String, ForeignKey
from sqlalchemy.orm import registry, relationship

metadata = MetaData()


user_table = Table(
    'user_account',
    metadata,
    Column('id', Integer, primary_key=True),
    Column('name', String(30)),
    Column('fullname', String(100)) #String으로 안보내지고 String(100) 으로 지정    
)

address_table = Table(
    'address',
    metadata,
    Column('id', Integer, primary_key=True),
    Column('user_id', ForeignKey('user_account.id'), nullable=False),
    Column('email_address', String(100), nullable=False)    #String으로 안보내지고 String(100) 으로 지정    

)
print(type(user_table.c.name)) # <class 'sqlalchemy.sql.schema.Column'>
print(type(type("Username: " + user_table.c.name)) # <class 'sqlalchemy.sql.elements.BinaryExpression'>
```

2021-07-25 04:54 UTC, Hyeonproject commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +>>> select(address_table.c.email_address)
```suggestion
>>> select(address_table.c.email_address).
```
.이 안 붙은거 같아서 작게나마 적어봅니다.

2021-07-25 08:44 UTC, heumsi requested changes
이전보다 확실히 읽기 좋아졌네요!
저도 2회독하며 다시 공부할 수 있었습니다 ㅋㅋ

인라인 코드가 통일되지 않은 부분이 있는데요. (예를 들면 어디는 `FROM` 절 이라고 표현하고, 어디는 FROM절 이라고 표현되고 있네요. ) 이 부분은.. 추후에 문서 다 작성하고 일괄적으로 한번 표준화하는 작업 때 다시 고쳐보죠.

어색한 부분 + 빠진 부분은 제가 서제션 드렸습니다.
고생하셨어요!

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +where 절을 통한 join을 구현 할 경우 아래와 같이 작성 가능합니다.
```suggestion
WHERE 절을 통한 JOIN을 구현해야 할 때, 아래와 같이 작성 가능합니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +...
```suggestion
>>> print(
...     select(Address.email_address).
...         where(
...             and_(
...                 or_(User.name == 'squidward', User.name == 'sandy'),
...                 Address.user_id == User.id
...             )
...         )
...  )
"""
SELECT address.email_address
FROM address, user_account
WHERE (user_account.name = :name_1 OR user_account.name = :name_2)
AND address.user_id = user_account.id
"""
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +>>>select(User).filter_by(name='spongebob', fullname='Spongebob Squarepants')
```suggestion
>>> print(
...     select(User).filter_by(name='spongebob', fullname='Spongebob Squarepants')
... )
"""
SELECT user_account.id, user_account.name, user_account.fullname
FROM user_account
WHERE user_account.name = :name_1 AND user_account.fullname = :fullname_1
"""
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +하나는 `Select.join()`메서드로 명시적으로 `JOIN` 할 왼쪽에 들어갈 테이블, 오른 쪽에 들어 갈 테이블을 직접 지정할 수 있습니다
```suggestion
하나는 `Select.join()`메서드로 명시적으로 `JOIN` 할 왼쪽에 들어갈 테이블, 오른쪽에 들어 갈 테이블을 직접 지정할 수 있습니다
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +다른 하나는 `select.join()`메서드로 오른쪽에 들어갈 테이블만 명시적으로 적어주고
```suggestion
다른 하나는 `Select.join()`메서드로 오른쪽에 들어갈 테이블만 명시적으로 적어주고 
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +... )
```suggestion
# 위와 동일한 표현이지만, 조인할 왼쪽 테이블(user_table)은 암시적으로 표현됩니다.
>>> print(
...     select(user_table.c.name, address_table.c.email_address).
...     join(address_table)
... )
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +사실 이 전의 예제에서 `Select.select_from()`이나 ` select.join()`을 이용해 두 테이블을 `JOIN`할 때 암시적으로 `ON절`이 세팅되었답니다.
```suggestion
사실 이 전의 예제에서 `Select.select_from()`이나 `select.join()`을 이용해 두 테이블을 `JOIN`할 때 암시적으로 `ON`절이 세팅되었답니다.    
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +만약에 `Join`의 대상인 두 개의 테이블에서 이러한 제약 key가 없을 경우 `ON` 절을 직접 지정해야 합니다. 이러한 기능은 `Select.join()`과 `Select.join_from()`메서드 둘 다 명시적으로 `ON`절을 세팅할 수 있습니다.
```suggestion
만약에 `Join`의 대상인 두 개의 테이블에서 이러한 제약 key가 없을 경우 `ON`절을 직접 지정해야 합니다. 이러한 기능은 `Select.join()`나 `Select.join_from()`메서드에 파라미터 전달을 통해 명시적으로 `ON`절을 세팅할 수 있습니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +
```suggestion
""" 위 구문은 아래 SQL을 표현합니다.
SELECT user_account.name, count(address.id) AS count
FROM user_account JOIN address ON user_account.id = address.user_id GROUP BY user_account.name
HAVING count(address.id) > ?
[...] (1,)
"""

```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +>>> # 방금 만든 테이블 별명으로 컬럼에 접근하려면 Alia.c.컬럼명으로 접근해야합니다.
```suggestion
>>> # 방금 만든 테이블 별명으로 컬럼에 접근하려면 Alias.c.컬럼명으로 접근해야합니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +
```suggestion
>>> subq = select(
...     func.count(address_table.c.id).label("count"),
...     address_table.c.user_id
... ).group_by(address_table.c.user_id).subquery()
>>> print(subq)
"""
SELECT count(address.id) AS count, address.user_id
FROM address GROUP BY address.user_id
"""

>>> stmt = select(
...    user_table.c.name,
...    user_table.c.fullname,
...    subq.c.count
... ).join_from(user_table, subq) # ON절은 두 개의 테이블이 이미 foreigh key로 제약이 걸려있어 자동 바인딩된다.
>>> print(stmt)
"""
SELECT user_account.name, user_account.fullname, anon_1.count
FROM user_account JOIN (SELECT count(address.id) AS count, address.user_id AS user_id
FROM address GROUP BY address.user_id) AS anon_1 ON user_account.id = anon_1.user_id
"""
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +이 섹션에서는 일반적으로 SELECT의 FROM 절에 있는 서브 쿼리에 대해 설명합니다. 서브쿼리와 유사한 방식으로 사용되지만 추가 기능이 포함된 CTE도 다룹니다.
```suggestion
이 섹션에서는 일반적으로 SELECT의 FROM 절에 있는 서브 쿼리에 대해 설명합니다. 서브쿼리와 유사한 방식으로 사용되지만 추가 기능이 포함된 CTE도 다룹니다.

> CTE(Common Table Expression)는 동일 쿼리 내에서 여러번 참조할 수 있게 하는 쿼리 내 임시 결과 집합입니다. [이 글](https://blog.sengwoolee.dev/84)에 CTE에 대해 잘 설명되어 있으니, 잘 모르시겠는 분들은 참고하시면 좋습니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +SQLAlchemy에서 CTE 구문을 사용하는 방법은 서브 쿼리 구문이 사용되는 방식과 거의 동일합니다. 대신 `Select.subquery()` 메서드의 호출을 Select.cte()를 사용하도록 변경하여 결과 객체를 FROM 요소로 사용할 수 있습니다.
```suggestion
SQLAlchemy에서 CTE 구문을 사용하는 방법은 서브 쿼리 구문이 사용되는 방식과 거의 동일합니다. 대신 `Select.subquery()` 메서드의 호출을 `Select.cte()`를 사용하도록 변경하여 결과 객체를 FROM 요소로 사용할 수 있습니다. 
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +... ).join_from(user_table, subq)
```suggestion
... ).join_from(user_table, subq)

>>> print(stmt)
"""
WITH anon_1 AS
(SELECT count(address.id) AS count, address.user_id AS user_id
FROM address GROUP BY address.user_id)
 SELECT user_account.name, user_account.fullname, anon_1.count
FROM user_account JOIN anon_1 ON user_account.id = anon_1.user_id
"""
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +...         print(f"{user} {address}")
```suggestion
...         print(f"{user} {address}")

""" 위 구문은 아래 쿼리를 표현합니다.
SELECT user_account.id, user_account.name, user_account.fullname,
anon_1.id AS id_1, anon_1.email_address, anon_1.user_id
FROM user_account JOIN
(SELECT address.id AS id, address.email_address AS email_address, address.user_id AS user_id
FROM address
WHERE address.email_address NOT LIKE ?) AS anon_1 ON user_account.id = anon_1.user_id
ORDER BY user_account.id, anon_1.id
[...] ('%@aol.com',)
"""

User(id=1, name='spongebob', fullname='Spongebob Squarepants') Address(id=1, email_address='spongebob@sqlalchemy.org')
User(id=2, name='sandy', fullname='Sandy Cheeks') Address(id=2, email_address='sandy@sqlalchemy.org')
User(id=2, name='sandy', fullname='Sandy Cheeks') Address(id=3, email_address='sandy@squirrelpower.org')
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> + - 서브쿼리란 하나의 SQL문에 속한 `SELECT`문을 말하고 서브 쿼리의 바깥 쪽에 있는 SQL문을 `메인 쿼리`라고 합니다.
```suggestion
 - "서브쿼리"란 하나의 SQL문에 속한 `SELECT`문을 말하고 서브 쿼리의 바깥 쪽에 있는 SQL문을 "메인 쿼리"라고 합니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +스칼라 서브쿼리는 앞에서 설명했던 [그룹 합수]()와 같이 쓰이고는 합니다.
```suggestion
스칼라 서브쿼리는 앞에서 설명했던 그룹 함수와 같이 쓰이고는 합니다.   
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +>>> # Select.scalar_subquery()를 이용해 구현한 스칼라 서브 쿼리
```suggestion
# Select.scalar_subquery()를 이용해 구현한 스칼라 서브 쿼리
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +...             scalar_subquery()
```suggestion
>>> subq = select(func.count(address_table.c.id)).
...             where(user_table.c.id == address_table.c.user_id).
...             scalar_subquery()
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +SQLAlchemy에서 `Select`구문은 `union()`, `intersect()`, `except_()` 혹은
```suggestion
SQLAlchemy에서 `Select` 객체에 대하여 `union()`, `intersect()`, `except_()` 혹은 
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +SQLAlchemy는 `SelectBase.exists()`메서드를 통해 `Exists`객체를 만들어  EXISTS구문을 구현합니다.
```suggestion
SQLAlchemy는 `SelectBase.exists()`메서드를 통해 `Exists`객체를 만들어 `EXISTS` 구문을 구현합니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +한편 EXISTS 구문은 부정으로 사용되지 않는 경우가 더 많습니다.
```suggestion
한편 `EXISTS` 구문은 부정으로 사용되지 않는 경우가 더 많습니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +...     print(result.all())
```suggestion
...     result = conn.execute(stmt)
...     print(result.all())

[('patrick',)]
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +  #SQLite에서 CURRENT_TIMESTAMP함수로 쓰일 경우
```suggestion
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +  ...     print(result.all())
```suggestion
  ...     print(result.all())

  [(datetime.datetime(...),)]
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +`FunctionElement.over.order_by`를 사용하여 ORDER BY 절을 사용할 수도 있습니다.
```suggestion
`FunctionElement.over.order_by`를 사용하여 `ORDER BY` 절을 사용할 수도 있습니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +각 각은 `FunctionElement.within_group()`메서드를 갖고 있습니다.
```suggestion
각각은 `FunctionElement.within_group()`메서드를 갖고 있습니다.
```

2021-07-25 08:44 UTC, heumsi commented on tutorial/5. 데이터 핸들링하기 - Select구문.md
> +`Select.select_from()`을 사용하는 또 다른 경우는 우리가 조회하고 싶은 컬럼들을 통해 암시적으로 FROM절을 세팅할 수 없는 경우입니다.   예를 들면 일반적인 SQL 쿼리문에서 `count(*)`를 조회하기 위해선  SQLAlchemy의 `sqlalchemy.sql.expression.func`를 사용해야합니다.
```suggestion
`Select.select_from()`을 사용하는 또 다른 경우는 우리가 조회하고 싶은 컬럼들을 통해 암시적으로 `FROM` 절을 세팅할 수 없는 경우입니다.   예를 들면 일반적인 SQL 쿼리문에서 `count(*)`를 조회하기 위해선  SQLAlchemy의 `sqlalchemy.sql.expression.func`를 사용해야합니다.
```

2021-07-26 12:48 UTC, heumsi approved these changes

2021-07-26 12:49 UTC, merged