Tutorial - 6. Data Manipulation with the ORM
SoogoonSoogoonPythonists/sqlalchemy-for-pythonist pull request #22
Opened 2021-07-28 16:39 UTC by comnamu18

#7 관련 작업 1차 초안 완료해서 올립니다.

내용이 많지는 않은데, 설명이 대부분이라 용어를 어느 정도까지 번역하고 어느 정도까지 내용을 축약할지 고민이 많이 됐네요..

DB관련 기초 지식이 부족하여 설명 중 미흡한 부분이 많을 것 같습니다. 너그러이 봐주시고 PR 주시면 감사하겠습니다!

2021-07-30 16:43 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +5장까지는 CORE 관점에서 SQL 언어를 활용하는 방식에 초점을 맞췄습니다. 이번 장에서는 Session의 구성 요소와 수명 주기, 상호 작용하는 방법을 설명합니다.
객체들은 ``로 감싸주면 좋을 것 같아요~!!

2021-07-30 17:12 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +5장까지는 CORE 관점에서 SQL 언어를 활용하는 방식에 초점을 맞췄습니다. 이번 장에서는 Session의 구성 요소와 수명 주기, 상호 작용하는 방법을 설명합니다.
Session을 ``마크다운 코드블럭으로 감싸주면 좋을 것 같아요~!

2021-07-30 17:13 UTC, icehongssii reviewed
ㅇ

2021-07-30 17:19 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +Session 객체는 ORM을 사용할 때 `Insert` 를 구성하고 transaction에서 이를 내보내는 역할을 합니다.
```suggestion
`Session` 객체는 ORM을 사용할 때 `Insert` 를 구성하고 transaction에서 이를 내보내는 역할을 합니다.
```

2021-07-30 17:28 UTC, icehongssii requested changes

2021-07-30 17:28 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +Session 객체는 ORM을 사용할 때 `Insert` 를 구성하고 transaction에서 이를 내보내는 역할을 합니다.
1. Session은  SqlAlchemy에서 제공하는 클래스이니 ``마크다운 블럭으로 감싸면 좋을  것 같아요!!
2. [3. 트랜잭션 및 DBAPI 작업.md](https://github.com/SoogoonSoogoonPythonists/sqlalchemy-for-pythonist/blob/main/src/tutorial/3.%20%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98%20%EB%B0%8F%20DBAPI%20%EC%9E%91%EC%97%85.md) 여기에서  transaction을 트랜젝션으로 번역하셔서 여기서도 트랜젝션으로 바꾸는게 좋을 것 같습니다..

2021-08-01 04:14 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +Session 객체는 ORM을 사용할 때 `Insert` 를 구성하고 transaction에서 이를 내보내는 역할을 합니다.
제가 이전 pr 리뷰들 파악을 잘 못한건지.. 혹시 마크다운 블록으로 감싸는 규칙이 따로 있을까요?? flushing이 꽤나 중요한 키워드 같아서 일단 블록으로 감쌌었습니다.

2021-08-01 07:11 UTC, icehongssii reviewed
모두 바꾼거는 아니지만 가능한 아래 내용으로 수정(?)하려고 노력했습니다.(rolling back과 세션 종료하기부븐을 제외하고 리뷰했스빈다)

- User, sandy같은 인스턴스를 ``마크다운 블럭으로 감쌌습니다
- SELECT user_account.id, user_account.name, user_account.fullname같은 쿼리문을 “”” 으로 감쌌습니다
- sqlalchemy에서 지원하는 클래스들, Session등을 마크다운 블럭으로 감쌌습니다.
- flush/autoflush는 그대로 사용하되 마크다운 블럭을 제거했습니다.
- 이해가 가지 않는 부분은 제가 삭제하거나 수정했습니다 (이부분은 코멘트 남겼습니다!!)
-

2021-08-01 07:11 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +위에서 언급한 두번째 방법인 `ORM 사용 업데이트`를 사용하면, 한 번에 많은 행에 영향을 줄 수 있는 일반 SQL `UPDATE` 문을 사용할 수 있습니다.
```suggestion
ORM을 통해 `UPDATE` 하는 마지막 방법으로 `ORM 사용 업데이트`를 명시적으로 사용하는 방법이 있습니다. 이를 사용하면  한 번에 많은 행에 영향을 줄 수 있는 일반 SQL `UPDATE` 문을 사용할 수 있습니다. 
```
- 위에서 언급한 방법을 조금 더 명시적으로 적으려고 했습니다

2021-08-01 07:37 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +1. 세션에서 사용하는 작업 단위 프로세스(`unit of work`)의 일부로 자동으로 내보내지며, 여기서 `UPDATE` 문은 변경 사항이 있는 개별 개체에 해당하는 기본 키별로 내보내집니다.
저도 처음 들어보는 패턴이라 [관련 링크](https://zetlos.tistory.com/1179902868) 등을 통해서 찾아보니 DB에서 보통 쓰이는 패턴 같네요. 

간단히 이해하기론, 작업 단위 별로 프로세스가 진행된다 는 것이고, 여기서 말하는 작업 단위라는 건, UPDATE 에서 기본 키 별로 각각의 객체를 부분(Unit) 부분 실행하면서 동작한다, 라고 이해했습니다.

설명을 어떻게 풀어써야 할지 난감하네요..

2021-08-01 07:39 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +`Column`과 Class 생성자의 keyword arguments를 매핑하여 객체를 구성합니다.
DB 칼럼이 User 객체의 attribute들이 Python class 생성자의 keyword arguments를 통해서 매핑된다. 라는 내용인데 해당 부분 삭제된 이유가 있을까요??

2021-08-01 07:41 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +1. 세션에서 사용하는 작업 단위 프로세스(`unit of work`)의 일부로 자동으로 내보내지며, 여기서 `UPDATE` 문은 변경 사항이 있는 개별 개체에 해당하는 기본 키별로 내보내집니다.
@comnamu18 
저 같은 [경우](https://github.com/SoogoonSoogoonPythonists/sqlalchemy-for-pythonist/blob/main/src/tutorial/5.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%95%B8%EB%93%A4%EB%A7%81%20-%20Core%2C%20ORM%EC%9C%BC%EB%A1%9C%20%ED%96%89%20%EC%A1%B0%ED%9A%8C%ED%95%98%EA%B8%B0.md#%EC%8A%A4%EC%B9%BC%EB%9D%BC-%EC%84%9C%EB%B8%8C-%EC%BF%BC%EB%A6%AC-%EC%83%81%ED%98%B8%EC%97%B0%EA%B4%80-%EC%BF%BC%EB%A6%AC)는  sqlalchemy 튜토리얼 원문에는 소개가 안되어있는데 이해를 위해 서브쿼리 설명을 잠간 담기도 했고
저도 이해가 안가는경우는 건너 뛰거나 아니면 참고링크 [이런식](https://github.com/SoogoonSoogoonPythonists/sqlalchemy-for-pythonist/blob/main/src/tutorial/5.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%95%B8%EB%93%A4%EB%A7%81%20-%20Core%2C%20ORM%EC%9C%BC%EB%A1%9C%20%ED%96%89%20%EC%A1%B0%ED%9A%8C%ED%95%98%EA%B8%B0.md#%EC%84%9C%EB%B8%8C%EC%BF%BC%EB%A6%AC%EC%99%80-cte)으로 넣기도 했습니다@_ㅠ

2021-08-01 07:42 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +Session 객체는 `unit of work` 패턴을 사용합니다. 변경 사항을 누적하지만, 필요할 때까지는 실제로 데이터베이스와 통신을 하지 않습니다. 이를 통해 주어진 `pending` 집합을 트랜잭션에서 더 효율적인 SQL DML으로 사용할 수 있습니다. 현재의 변경된 사항들을 실제로 Database에 SQL을 통해 내보내는 작업을 `Flushing
line 43에서 언급한 pending 상태가 이 부분에서 의미를 가지게 되는 것 같습니다.
- 이런 동작 방식을 통해서 위에서 언급한 pending 상태의 객체들이 더 효율적인 SQL DML로 사용됩니다.
이런식으로 추가하는 건 어떻게 생각하시나요?

2021-08-01 07:45 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +> - `SQLite`의 경우 한 번에 한 열을 `INSERT` 해야 자동 증가 기능을 사용할 수 있습니다.(`PostgreSQL`, `IDENTITY` 등 다른 다양한 DB들의 경우에도 이처럼 동작합니다.)
IDENTITY, SERIAL이 PostgreSQL이나 MySQL 같은 독립적인 DB 프로그램(?) 인 줄 알았습니다.. 감사합니다.

2021-08-01 07:48 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +`Column`과 Class 생성자의 keyword arguments를 매핑하여 객체를 구성합니다.
```
`INSERT` 될 잠재적인 데이터베이스 행을 나타내는 두 개의 `User` 객체를 만듭니다.
`Column`과 Class 생성자의 keyword arguments를 매핑하여 객체를 구성합니다.
ORM 매핑에 의해 자동으로 생성된 `__init__()` 생성자 덕에 생성자의 열 이름을 키로 사용하여 각 객체를 생성할 수 있습니다.
```
가 원래 문단인데요!! 여기서 세번째 문장
`ORM 매핑에 의해 자동으로 생성된 __init__() 생성자 덕에 생성자의 열 이름을 키로 사용하여 각 객체를 생성할 수 있습니다.`가  keyword arguments나타내는 내용과 중복되는 내용이라 지웠습니다!! 
제가 suggestion한대로 다 진행하실 필요도 없고 @comnamu18 보시기에 자연스럽다고 생각하시는 부분으로 진행해주시면 될 것 같습니다 ㅎㅎㅎㅎ

2021-08-01 07:48 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +1. 세션에서 사용하는 작업 단위 프로세스(`unit of work`)의 일부로 자동으로 내보내지며, 여기서 `UPDATE` 문은 변경 사항이 있는 개별 개체에 해당하는 기본 키별로 내보내집니다.
원문에서 TIP 방식으로 넣는 것처럼 넣으면 되겠네요.. unit of work는 위에서 먼저 언급이 되었으니 거기서 설명을 하고 요 부분은 말을 조금 더 자연스럽게 바꿔야겠네요. 감사합니다.

2021-08-01 08:34 UTC, definity-smileY reviewed
전체적으로 쿼리,코드가 많은 부분을 담당하셨는데 출력문과 쿼리문을 구분지어서 가독성이 좋게 하면 어떨까 하는 바람입니다. !
한 주 동안 문서정리하시느라 고생많으셨습니다. 잘 읽었습니다.  :)

2021-08-01 08:34 UTC, definity-smileY commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +> -  `psycopg2`와 같이 한번에 많은 데이터에 대한 기본 키 정보를 제공 받을 수 있는 database 백엔드가 연결되어 있다면, ORM은 이를 최적화하여 많은 열을 한번에 `INSERT` 하도록 합니다.
```suggestion
> -  `psycopg2`와 같이 한번에 많은 데이터에 대한 기본 키 정보를 제공 받을 수 있는 데이터베이스가 연결되어 있다면, ORM은 이를 최적화하여 많은 열을 한번에 `INSERT` 하도록 합니다.
```
백엔드 단어를 안넣어도되지 않을까 생각해봅니다

2021-08-01 08:34 UTC, definity-smileY commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +`Identity Map`(이하 `ID Map`)은 현재 메모리에 로드된 모든 객체를 기본 키 ID에 연결하는 메모리 내 저장소입니다.
```suggestion
`Identity Map`(`ID Map`)은 현재 메모리에 로드된 모든 객체를 기본 키 ID에 연결하는 메모리 내 저장소입니다.
```

2021-08-01 08:34 UTC, definity-smileY commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +## ORM 객체 UPDATE하기
```suggestion
## ORM 객체 `UPDATE`하기 
```

2021-08-01 08:34 UTC, definity-smileY commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +[...] (4,)
```suggestion
```python
# 예시를 위한 작업일 뿐, 실제로 delete에서 필요한 작업은 아닙니다.
squidward = session.get(User, 4)
SELECT user_account.id AS user_account_id, user_account.name AS user_account_name,
user_account.fullname AS user_account_fullname
FROM user_account
WHERE user_account.id = ?
[...] (4,)
```

2021-08-01 08:34 UTC, definity-smileY commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +> `detached` 상태의 개체는 되도록이면 사용을 지양해야 합니다. Session이 닫히면 이전에 연결된 모든 개체에 대한 참조도 정리합니다. 일반적으로 `detached`된 객체가 필요한 경우는  웹 어플리케이션에서 방금 커밋된 개체를 뷰에서 렌더링되기 전에 세션이 닫힌 경우가 있습니다. 이 경우 `Session.expire_on_commit` 플
```suggestion
- `detached` 상태의 개체는 되도록이면 사용을 지양해야 합니다. Session이 닫히면 이전에 연결된 모든 개체에 대한 참조도 정리합니다. 일반적으로 `detached`된 객체가 필요한 경우는  웹 어플리케이션에서 방금 커밋된 개체를 뷰에서 렌더링되기 전에 세션이 닫힌 경우가 있습니다. 이 경우 `Session.expire_on_commit` 플래그를 False로 설정합니다.
```

2021-08-01 13:12 UTC, heumsi commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +Session 객체는 ORM을 사용할 때 `Insert` 를 구성하고 transaction에서 이를 내보내는 역할을 합니다.
> 혹시 마크다운 블록으로 감싸는 규칙이 따로 있을까요??

일단 규칙은 따로 없었습니다. 이슈 작업들 다 완료하고, 다시 한번 용어, 블락 정리하려고 합니다.

2021-08-02 16:03 UTC, icehongssii reviewed
ORM 객체를 삭제하기부터 리뷰 달았습니다.  수고 하셨습니다!!

2021-08-02 16:03 UTC, icehongssii commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +`Session.rollback()`을 호출하면 트랜잭션을 롤백할 뿐만 아니라 현재 이 Session과 연결된 모든 객체가 `만료`됩니다. 이는 `지연 로딩`이라고 하는 프로세스를 사용하여 다음에 액세스할 때 스스로 새로 고쳐지는 효과가 있습니다.
```suggestion
`Session.rollback()`을 호출하면 트랜잭션을 롤백할 뿐만 아니라 현재 이 `Session`과 연결된 모든 객체를 만료 상태로 바꿉니다. 이러한 상태 변경은 다음에 객체에 접근 할 때 스스로 새로 고침을 하는 효과가 있고 이러한 프로세스를 `지연 로딩` 이라고 합니다.
```

2021-08-02 21:22 UTC, Hyeonproject reviewed
다들 너무 리뷰를 잘해놨기에 큰 변경은 없었습니다. 나중에 master 브렌치에 커밋이 되어도 전체적으로 읽고 부족한 부분을 채워넣으며 수정할 생각입니다.

2021-08-03 15:02 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +이전 예에서 우리는 Python Dict를 사용하여 `INSERT`를 실행하였지만, ORM에서는 테이블 메타데이터 정의에서 정의한 사용자 정의 Python 클래스를 직접 사용합니다.
```suggestion
이전 과정에서 우리는 `Python Dict`를 사용하여 `INSERT`를 실행하였습니다.

ORM에서는 테이블 메타데이터 정의에서 정의한 사용자 정의 Python 클래스를 직접 사용합니다.
```
line split해두신건 MD파일 미리보기로 보았을 때, 해당 SUGGESTION 부분이 조금 이상하게 보여서.. 임의로 이와같이 2라인으로 쪼개게 하였습니다.

2021-08-03 15:12 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +`UPDATE`와 마찬가지로 `Session.execute()`와 함께 `delete()` 구문을 사용하는 `DELETE`의 ORM 지원 버전도 있습니다. 또한 지정된 삭제 조건과 일치하는 만료되지 않은 객체가 Session에서 "삭제됨"으로 자동 표시되는 기능도 있습니다.
다른 상태 (PENDING, EXPIRED, 등등)에 대해서는 추가적인 링크로 설명이 붙어 있지 않아서 굳이 여기에만 링크를 달기는 조금 혼동이 올 것 같습니다ㅠ

2021-08-03 15:23 UTC, comnamu18 commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +> `detached` 상태의 개체는 되도록이면 사용을 지양해야 합니다. Session이 닫히면 이전에 연결된 모든 개체에 대한 참조도 정리합니다. 일반적으로 `detached`된 객체가 필요한 경우는  웹 어플리케이션에서 방금 커밋된 개체를 뷰에서 렌더링되기 전에 세션이 닫힌 경우가 있습니다. 이 경우 `Session.expire_on_commit` 플
해당 부분은 원문에서 tip 에 해당하는 부분들을 특별히 표시하기 위해서 의도적으로 > 로 표시를 준 건데, 이와 관련해서 가이드라인이 있나요?? 이전 글에서도 TIP 부분은 이렇게 쓰였던 걸로 알고 있습니다.

2021-08-03 16:32 UTC, heumsi requested changes

2021-08-03 16:32 UTC, heumsi commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +  - 즉, 세션을 사용하여 일부 읽기 전용 작업을 수행한 다음, 닫을 때 트랜잭션이 롤백되었는지 확인하기 위해 Session.rollback()을 명시적으로 호출할 필요가 없습니다. 연결 풀이 이를 처리합니다.
```suggestion
  - 즉, 세션을 사용하여 일부 읽기 전용 작업을 수행한 다음, 닫을 때 트랜잭션이 롤백되었는지 확인하기 위해 `Session.rollback()`을 명시적으로 호출할 필요가 없습니다. 연결 풀이 이를 처리합니다.
```

2021-08-03 16:33 UTC, heumsi commented
해결된 리뷰들은 `resolve conversation` 버튼을 눌러 표시해주세요.
최종 머지 되기 전에 제가 vuepress 에 반영하는 작업을 해두겠습니다.

2021-08-03 16:34 UTC, heumsi commented
또한 

```
git fetch origin
git rebase origin/main 
```

한번만 해주시겠어요?
rebase 후에는 force push 해야 합니다.

2021-08-03 16:48 UTC, definity-smileY commented on src/tutorial/6. ORM으로 데이터 조작하기.md
> +> `detached` 상태의 개체는 되도록이면 사용을 지양해야 합니다. Session이 닫히면 이전에 연결된 모든 개체에 대한 참조도 정리합니다. 일반적으로 `detached`된 객체가 필요한 경우는  웹 어플리케이션에서 방금 커밋된 개체를 뷰에서 렌더링되기 전에 세션이 닫힌 경우가 있습니다. 이 경우 `Session.expire_on_commit` 플
네 제가 착오가 있엇네요 그대로 진행하면 될 것 같습니다 ㅎ

2021-08-03 17:07 UTC, comnamu18 commented
> 또한
> 
> ```
> git fetch origin
> git rebase origin/main 
> ```
> 
> 한번만 해주시겠어요?
> rebase 후에는 force push 해야 합니다.

해당 진행 후 아래와 같이 나옵니다. `git status`를 찍어보면 아래와 같이 나옵니다.

```
interactive rebase in progress; onto 357db50
Last command done (1 command done):
   pick 7b82f88 [tutorials] '1 - Overview' 를 '1. 튜토리얼 개요' 로 파일 이름을 수정하고 제목을 추가한다
Next commands to do (8 remaining commands):
   pick 6dc2ae7 [tutorials] '2. 연결 설정하기'를 작성한다
   pick 841a771 [tutorials] '3. 트랜잭션 및 DBAPI 작업' 을 작성한다
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'issue/7' on '357db50'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working tree clean
```

`git push origin issue/7`을 통해 현재 브랜치에 푸쉬하니 `Everything up-to-date` 라고만 나오고요.. rebase는 잘 안해서 모르겠는데 이게 원하던 동작 결과가 맞으신가요?

2021-08-03 17:21 UTC, comnamu18 commented
문서 6뿐 아니라 1~5에 대해서 타이틀이 바뀌어서(기존 : [챕터 No]. [챕터 제목] -> 현재 main : [챕터 제목]) 해당 부분들 conflict 나는거 직접 수정하였습니다.

수정하면서 몇가지 누락된 변경사항이 있을 수 있으니 내일이나 빠른 시일 내에 검토 같이 해보고 받아주시면 감사하겠습니다.

2021-08-03 23:40 UTC, heumsi commented
헉 리베이스 그냥 제가할걸 그랬네요.
수고하셨습니다!

2021-08-03 23:44 UTC, heumsi approved these changes

2021-08-03 23:46 UTC, merged