Tutorial - 7. Working with Related Objects
SoogoonSoogoonPythonists/sqlalchemy-for-pythonist pull request #24
Opened 2021-08-04 17:58 UTC by definity-smileY

문서를 읽다가 이틀을 소비하긴했는데 제가 맡은 파트가 SQLAlchemy를 사용하는 근본적인 기술적인 문서를 다루는 것 같습니다.
SQLAlchemy이 관심이 있거나 기술적인 질문들이 이 부분에서 많이 나올 것 같은 부분이라 많은 채찍(관심)을 주시면 감사하겠습니다!
저 또한 읽으면서 이해 안되는 부분들이 많고 조금 더 직관적이고 이해하기 쉽게 생각하려했는데 쉽지 않았습니다.

문서 용어 통일과 수정은 리뷰받으면서 수정해보도록 하겠습니다!
그리고 맡은 문서 작업동안 Chapter 6를 pull안해서 관련된 섹션으로 이동하기등 하지 못한 부분이 있습니다. 이것 또한 pull한 후에 순차적으로 수정하겠습니다.

2021-08-05 15:34 UTC, heumsi requested changes
저는 읽으면서 한 30% 정도만 이해가 가네요 ㅋㅋㅋㅋ...
왤케 어렵죠... 흑흑..

정리해주시느라 고생하셨습니다.

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +먼저 우리는 [매핑된 객체 선언] 섹션에서 매핑된 객체 예제 구성을 사용했습니다.
매핑된 객체 선언 섹션이 어디일까요? 챕터 링크를 걸어주고 해당 챕터 제목이랑 일치시켜주시면 좋을거 같아용

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +다음 섹션에서 `relationship()` 객체의 인스턴트가 어떤 역할을 하는지, 동작하는지 보겠습니다.
```suggestion
다음 섹션에서 `relationship()` 객체의 인스턴스가 어떤 역할을 하는지, 동작하는지 보겠습니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +새로운 `User` 객체를 만들면 `.addresses` 컬렉션이 나타나는데 `딕셔너리`나 `set`같은 다양한 컬렉션이 있는데 기본 컬렉션은 Python `리스트`인것을 알 수 있습니다.
```suggestion
새로운 `User` 객체를 만들면 `.addresses` 컬렉션이 나타나는데 `List` 객체임을 알 수 있습니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +User(id=None, name='pkrabs', fullname='Pearl Krabs')
앗 얘는 왜 `List` 가 아닌거에용?? (질문)

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +마지막단계에서 `Session.commit()` 을 호출하여 `u1` 객체에 생성된 기본 키를 볼 수 있게됩니다.
```suggestion
`Session.commit()` 을 호출한 이후에는 `u1` 객체에 생성된 기본 키를 볼 수 있게됩니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +> SQL 쿼리일경우
```suggestion
위 코드는 다음 쿼리를 실행하는 것과 같습니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +`u1` `User 객체에 연결된 `User.addresses` 컬렉션이 있습니다.
```suggestion
다음처럼 `u1.addresses` 에 연결된 객체들에도 `id`가 들어와있는 것을 볼 수 있습니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +> SQL 쿼리일경우
```suggestion
위 코드는 다음 쿼리를 실행하는 것과 같습니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +이 섹션에서는 매핑된 객체의 적용되는 `relationshiop()`을 소개하며, SQL 쿼리 구성을 자동화하는데 도움이 되는 여러 가지 방법으로 사용됩니다.
```suggestion
이 섹션에서는 `relationship()` 이 SQL 쿼리 구성을 자동화하는데 도움이 되는 여러 가지 방법을 소개합니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +`relation()`으로 생성된 ON 절에 조건을 추가할 수 있습니다. 이 기능은 관계된 경로에 대한 특정 조인의 범위를 신속하게 제한하는 방법뿐만 아니라 마지막 센셔에서 소개하는 로더 전략 구성과 같은 사용 사례에도 유용합니다.
```suggestion
`relation()`으로 생성된 ON 절에 조건을 추가할 수 있습니다. 이 기능은 관계된 경로에 대한 특정 조인의 범위를 신속하게 제한하는 방법뿐만 아니라 마지막 섹션에서 소개하는 로더 전략 구성과 같은 사용 사례에도 유용합니다.  
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +`Session.execute()` 호출하는 동안 데이터베이스에서는 두 개의 SELECT 문이 생성되고 두 번째는 관련 `Address 객체를 가져오는 것입니다.
```suggestion
`Session.execute()` 호출하는 동안 데이터베이스에서는 두 개의 SELECT 문이 생성되고 두 번째는 관련 `Address` 객체를 가져오는 것입니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +`relationship()`에 명시된 테이블을 SELECT JOIN하여 모든 테이블의 데이터들을 한꺼번에 가져오는 방식으로 `Address 객체에 연결된 사용자가 있는 다음과 같은 경우에 OUTER JOIN이 아닌 INNER JOIN을 사용할 수 있습니다.
```suggestion
`relationship()`에 명시된 테이블을 SELECT JOIN하여 모든 테이블의 데이터들을 한꺼번에 가져오는 방식으로 `Address` 객체에 연결된 사용자가 있는 다음과 같은 경우에 OUTER JOIN이 아닌 INNER JOIN을 사용할 수 있습니다.
```

2021-08-05 15:34 UTC, heumsi commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +### reaise loading 방식
```suggestion
### raise loading 방식
```

2021-08-07 13:58 UTC, Hyeonproject commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +두개의 `relationshiop()` 객체 간의 `relationship.back_populates` 을 사용한 동기화 결과라고 할 수 있습니다.
```suggestion
두개의 `relationshiop()` 객체 간의 `relationship.back_populates` 을 사용한 동기화 결과입니다.
```
과감하게 결과라고 적어봅시다.

2021-08-08 07:45 UTC, definity-smileY commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +먼저 우리는 [매핑된 객체 선언] 섹션에서 매핑된 객체 예제 구성을 사용했습니다.
감사합니다 :) 제목과 동일한 해당 링크 수정하겠습니다.

2021-08-08 09:22 UTC, definity-smileY commented on src/tutorial/7. SQLAlchemy - ORM 다루기.md
> +User(id=None, name='pkrabs', fullname='Pearl Krabs')
저또한 완벽히 이해하지 못한 상황에서 답변드리기가 애매하네요ㅠㅠ 이해하신분이 있으시다면 리뷰달아주시면 감사하겠습니다.

2021-08-10 14:18 UTC, heumsi approved these changes

2021-08-10 14:22 UTC, heumsi approved these changes

2021-08-10 14:22 UTC, merged