[docs] 컨트리뷰션 가이드 및 관련 가이드를 작성한다
SoogoonSoogoonPythonists/sqlalchemy-for-pythonist pull request #32
Opened 2023-11-26 12:50 UTC by s3ich4n

## 작업사항

- `CONTRIBUTING.md` 파일 추가
- `vuepress` 로컬 구동방안 추가
  - @hyeonprojects 님이 [여기서](https://github.com/SoogoonSoogoonPythonists/sqlalchemy-for-pythonist/pull/30#issue-2010749637) 리포트하신 내용을 문서화

2023-11-26 13:29 UTC, heumsi requested changes
기여해주셔서 감사합니다. 코멘트 확인 부탁드립니다.

2023-11-26 13:29 UTC, heumsi commented on CONTRIBUTIONS.md
> +- [프로젝트 팀 채널에 참여하세요](#프로젝트-팀-채널에-참여하세요)
```suggestion
```

아래 내용을 보니 heading depth가 다른데, 목차에서는 모두 동일 depth로 표현되고 있네요.
목차에서도 마찬가지로 depth를 표현해주시면 좋을거 같습니다.

GitHub에서 이미 좌측 상단에 ToC를 제공하기 때문에, 별도의 ToC를 우리가 적어줄 필요는 없을거 같습니다.
ToC는 특히 문서 확장 시 관리 포인트가 별도로 하나 늘어나서, 번거롭다는 생각이 듭니다.

2023-11-26 13:29 UTC, heumsi commented on CONTRIBUTIONS.md
> +```
커밋 메시지는 `[작업 범위] ~한다` 의 룰을 현재 가지고 있습니다.

ex. `[tutorial] Section 1 내용을 추가한다`

따라서 이에 맞게 수정해주셔야 할거 같네요.

2023-11-26 13:29 UTC, heumsi commented on CONTRIBUTIONS.md
> +README 페이지에 가이드된 Slack 워크스페이스로 오시면 됩니다([📎 슬랙 채널 참여](https://join.slack.com/t/soogoonx2pythonists/shared_invite/zt-t8kvz57l-j~qJOhSP47annEB31QOLIQ)).
링크에 접속해보니 유효하지 않다고 나옵니다.

2023-11-26 13:29 UTC, heumsi commented on README.md
>  현재 아래 하나의 문서를 정리한 상태입니다.
`CONTRIBUTIONS.md` 에 대한 링크를 `README.md` 에도 넣으면 좋겠군요!

2023-11-26 13:29 UTC, heumsi commented on CONTRIBUTIONS.md
> +README 페이지에 가이드된 Slack 워크스페이스로 오시면 됩니다([📎 슬랙 채널 참여](https://join.slack.com/t/soogoonx2pythonists/shared_invite/zt-t8kvz57l-j~qJOhSP47annEB31QOLIQ)).
아래 링크로 바꿔주시면 될거 같습니다.

https://join.slack.com/t/soogoonx2pythonists/shared_invite/zt-27rth6utw-8qibkZV4~TRXp8qosUniLQ

2023-11-26 13:29 UTC, heumsi commented on CONTRIBUTIONS.md
> +README 페이지에 가이드된 Slack 워크스페이스로 오시면 됩니다([📎 슬랙 채널 참여](https://join.slack.com/t/soogoonx2pythonists/shared_invite/zt-t8kvz57l-j~qJOhSP47annEB31QOLIQ)).
`README.md` 에 있는 링크도 동일하게 바꿔주시겠어요?

2023-11-26 14:35 UTC, s3ich4n commented on CONTRIBUTIONS.md
> +```
수정 완료하였습니다. 갑사합니다.

2023-11-26 14:35 UTC, s3ich4n commented on CONTRIBUTIONS.md
> +README 페이지에 가이드된 Slack 워크스페이스로 오시면 됩니다([📎 슬랙 채널 참여](https://join.slack.com/t/soogoonx2pythonists/shared_invite/zt-t8kvz57l-j~qJOhSP47annEB31QOLIQ)).
동일하게 수정하였습니다. 감사합니다.

2023-11-26 14:38 UTC, s3ich4n commented on README.md
>  현재 아래 하나의 문서를 정리한 상태입니다.
추가하였습니다. 감사합니다.

2023-11-26 23:27 UTC, heumsi approved these changes
👍

2023-11-27 04:39 UTC, merged

2023-12-01 14:48 UTC, hyeonprojects commented
늦었지만 수고많으셨습니다!