[docs] 영문 초벌번역을 작성한다.
SoogoonSoogoonPythonists/sqlalchemy-for-pythonist pull request #34
Opened 2023-12-10 18:25 UTC by s3ich4n

## 작업사항

https://github.com/SoogoonSoogoonPythonists/sqlalchemy-for-pythonist/issues/33#issue-2034340457 까지 수행 완료

2023-12-27 14:11 UTC, heumsi requested changes
Suggestion만 반영 부탁드립니다.

2023-12-27 14:11 UTC, heumsi commented on src/en/tutorial/4. Working with Database Metadata.md
> +## Create a table object and add it to your metadata
```suggestion
## Creating a table object and add it to your metadata
```

2023-12-27 14:11 UTC, heumsi commented on src/en/tutorial/4. Working with Database Metadata.md
> +## Define table metadata the ORM way
```suggestion
## Defining table metadata the ORM way
```

2023-12-27 16:18 UTC, s3ich4n commented
Suggestion 사항에 대해 반영 완료하였습니다.

2023-12-28 03:20 UTC, heumsi submitted a review, later dismissed
LGTM 👍

2023-12-28 03:23 UTC, heumsi approved these changes
👍

2023-12-28 07:21 UTC, merged