Feature : Working with Database Metadata 번역
SoogoonSoogoonPythonists/sqlalchemy-for-pythonist pull request #4
Opened 2021-07-13 19:15 UTC by Hyeonproject

안녕하세요. 스터디 팀장님 다음으로 번역하게 된 주니어 개발자입니다.

처음 부족한 만큼 오히려 많은 피드백을 해주시면 좋겠습니다.

## 참고사항 및 말씀드리고 싶은 점
- 원문의 형식을 따르되 초보자가 이해하기 쉽게 작성할려고 노력했으면 많은 글보다 전체 흐름을 이해하기 위함에 집중했습니다.
- **전문용어 등의 언어 선택이 겹치지 않도록 검토**를 하였으나, 업무 끝나고 남은 에너지로 하다보니 놓치는 부분이 있을 수 있습니다.
- **저가 이해한 부분이 틀릴 경우 또는 언어 선택이 틀릴 경우에 피드백**을 부탁드립니다.
- **전체 흐름이 원할하지 않거나 이해하는데 막히는 부분이 있어도 피드백** 부탁드립니다.
- **글을 적은 구조와 언어체에 대해서도 피드백** 받습니다.
- 일부 내용은 이해를 돕기 위해서 일부러 첨삭한 부분도 있습니다.

PR을 했지만, 저 역시 검토와 수정을 이번 주 까지 할 예정입니다.

이 기회를 주신 스터티 팀장님에게 감사함을 표하며, 읽어주셔서 감사합니다.

2021-07-15 13:18 UTC, heumsi requested changes
생각보다 양이 많군요...
오늘은 `## ORM 지향 방식으로 테이블 메타데이터 정의` 까지 리뷰했습니다.
내일 마저 더 리뷰할게요!

초심자의 눈으로 이것저것 서제션을 드려보았습니다.
제 생각일 뿐이니 100% 정답은 아닙니다. 거르실 서제션은 거르셔도 됩니다. 다만 거르실 때 본인 생각을 적어주셨으면 좋겠습니다.

서제션은 오른쪽에 `FileChanged` 탭에서 `Add suggestion to batch` 로 일괄적으로 모든 서제션을 모아 한번의 커밋으로 반영할 수도 있습니다. 혹시 모르실까봐 적어둡니다!

2021-07-15 13:18 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +이런 객체로 된 코드를 데이터베이스 쿼리로 바꿔주는 메소드인 MetaData.create_all()을 사용하시면 됩니다.
```suggestion
지금까지 SQLAlchemy로 DB 테이블을 선언했습니다. 이제 이렇게 선언한 테이블이 실제 DB에 생성되도록 해봅시다.

다음처럼 `MetaData.create_all()` 을 실행합니다.
```

2021-07-15 13:18 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +코드는 다음과 같습니다.
```suggestion
먼저 다음처럼 테이블을 선언합니다.
```

2021-07-15 13:18 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +)
```suggestion
>>> from sqlalchemy import
>>> from sqlalchemy import Table, MetaData, Column, Integer, String

>>> metadata = MetaData(),  # 테이블들의 메타 정보를 담게될 객체입니다.

>>> user_table = Table(
...        'user_account',  # DB에 저장될 table 이름입니다.
...        metadata,
...        Column('id', Integer, primary_key=True),  # 이 테이블에 들어갈 컬럼입니다.
...        Column('name', String(30)),
...        Column('fullname', String),
...    )
```

2021-07-15 13:18 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +)
글로 길게 적혀있었지만, 잘 이해가 안갔습니다.
그냥 빠르게 코드를 보여주는게 더 직관적일거라 생각합니다.
오타 있는 부분도 정정하였습니다.

2021-07-15 13:18 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +...     Column('user_id', ForeignKey('user_account.id'), nullable=False),
```suggestion
...     Column('user_id', ForeignKey('user_account.id'), nullable=False),  # ForeignKey 객체로 외래 키를 선언합니다.

```

2021-07-15 13:18 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +COMMIT
```suggestion
>>> metadata.create_all(engine)

# 위 코드는 `metadata` 인스턴스에 기록된 모든 테이블들을 생성합니다.  
# 결과적으로는 아래 쿼리를 실행하게 됩니다.

BEGIN (implicit)
PRAGMA main.table_...info("user_account")
...
PRAGMA main.table_...info("address")
...
CREATE TABLE user_account (
    id INTEGER NOT NULL,
    name VARCHAR(30),
    fullname VARCHAR,
    PRIMARY KEY (id)
)
...
CREATE TABLE address (
    id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    email_address VARCHAR NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(user_id) REFERENCES user_account (id)
)
...
COMMIT
```

2021-07-15 13:18 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +위와 같은 DDL 코드로 바뀌게 됩니다.
```suggestion
```

2021-07-16 15:04 UTC, heumsi requested changes
저는 1차 리뷰 끝냈습니다!

전반적으로 비문이 조금 있고, 인라인 코드가 잘 안들어간 부분이 있는데, 다시 한 번 읽어보시며 이런 것들 잡아주시면 좋을거 같습니다. 너무 부담스럽거나 힘드시면 머지 전에 제가 작업해둘게요.

고생하셨습니다!

2021-07-16 15:04 UTC, heumsi commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +```
테이블 역생성이라고 하는게 조금 이해가 안가서 여쭈어 봅니다.

- 이게 위에 코어 방식으로 테이블을 생성한거랑 어떤게 다른거에요?
- 아래 `some_table` 에 `x`, `y` 컬럼이 등장했는데, 얘네들은 어디서 정의된건가요? 위 `Table` 코드에는 안보여서요

2021-07-16 16:24 UTC, comnamu18 commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +## 테이블 객체를 메타데이터 설정하기
> ## 테이블 객체로 메타데이터 설정하기
혹은
> ## 테이블 객체를 메타데이터로 설정하기

정말 사소한건데.. 말이 미묘하게 어색해서 남깁니다.

2021-07-17 08:47 UTC, definity-smileY commented on tutorial/4. 데이터베이스 메타데이터로 작업하기.md
> +각각 Table 객체를 코드를 통해서 명확하게 설정하거나, 기존으 데이터베이스에 정의되어 있는 것을 반영합니다.
```suggestion
각각의 Table 객체는 코드를 통해서 명확하게 설정하거나, 기존 데이터베이스에 정의되어 있는 것을 반영합니다.
```

1.  가독성 좋게 수정해보았습니다.
2. 기존으 -> 기존 로 수정했습니다.

2021-07-17 18:09 UTC, Hyeonproject reviewed
여러분들의 피드백을 잘 보았습니다.
대부분 맞는 말이기도 하고, 추천하신 방법이 옳은것 같아서 수정을 하게 되었습니다.

2021-07-17 18:37 UTC, merged

2021-07-18 07:51 UTC, Hyeonproject reviewed
f